[local]
localhost ansible_connection=local


[addc_servers]
windows-addc ansible_host=10.0.20.101


[wazuh_servers]
wazuh-server-1 ansible_host=10.0.20.10

[web_servers]
web-server-1 ansible_host=10.0.20.21

[db_servers]
db-server-1 ansible_host=10.0.20.30

[ftp_servers]
ftp-server-1 ansible_host=10.0.20.40

[linux_clients]
linux-1 ansible_host=10.0.20.200

[windows_clients]
windows-1 ansible_host=10.0.20.150

[servers:children]
wazuh_servers
web_servers
db_servers
ftp_servers

[linux_targets:children]
linux_clients
servers

[all_clients:children]
linux_clients
windows_clients
