---
# roles/wazuh-agent-windows/tasks/main.yml
# Installs Wazuh Agent on Windows 10 via WinRM

- name: Check if Wazuh Agent is already installed
  win_service:
    name: WazuhSvc
  register: wazuh_svc
  ignore_errors: yes

- name: Stop Wazuh Agent Service if running
  win_service:
    name: WazuhSvc
    state: stopped
  ignore_errors: yes

- name: Remove old wazuh agent installation folder
  win_file:
    path: 'C:\\Program Files (x86)\\ossec-agent'
    state: absent

- name: Ensure Temp directory exists
  win_file:
    path: C:\Temp
    state: directory

- name: Remove old Wazuh Client Keys
  win_file:
    path: 'C:\Program Files (x86)\ossec-agent\client.keys'
    state: absent

- name: Uninstall any existing Wazuh Agent
  win_command: >
    msiexec /x "C:\\Users\\Administrator\\Downloads\\wazuh-agent-4.14.5-1.msi" /qn /norestart
  ignore_errors: yes

- name: Download Wazuh Agent MSI installer (online mode)
  win_get_url:
    url: "https://packages.wazuh.com/4.x/windows/wazuh-agent-{{ wazuh_version }}-1.msi"
    dest: "C:\\Temp\\wazuh-agent.msi"
  when:
    - not (offline_mode | bool)

- name: Download Wazuh Agent MSI installer (offline mode - from local mirror)
  win_get_url:
    url: "{{ offline_files_url }}/wazuh-agent-{{ wazuh_version }}-1.msi"
    dest: "C:\\Temp\\wazuh-agent.msi"
  when:
    - offline_mode | bool

- name: Install Wazuh Agent silently
  win_command: >
    msiexec /i "C:\\Temp\\wazuh-agent.msi" /qn WAZUH_MANAGER="{{ wazuh_manager_ip }}" WAZUH_AGENT_NAME="{{ inventory_hostname }}" WAZUH_REGISTRATION_SERVER="{{ wazuh_manager_ip }}"
  ignore_errors: yes
  notify: restart wazuh-agent-windows

- name: Wait for Wazuh Agent to be ready
  win_wait_for:
    timeout: 30

- name: Ensure Wazuh Agent service is running
  win_service:
    name: WazuhSvc
    state: started
    start_mode: auto

- name: Open Wazuh Agent port in Windows Firewall
  win_firewall_rule:
    name: "Wazuh Agent"
    localport: 1614
    action: allow
    direction: out
    protocol: tcp
    state: present
    enabled: yes

- name: Verify Wazuh Agent service is running
  win_service:
    name: WazuhSvc
  register: wazuh_final_status

- name: Show Wazuh Agent status
  debug:
    msg: "Wazuh Agent on {{ inventory_hostname }} is {{ wazuh_final_status.state }} — reporting to {{ wazuh_manager_ip }}"
