# group_vars/addc_servers.yml
# WinRM connection settings for ADDC
ansible_user: Administrator
ansible_password: "Admin@123"
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore
ansible_winrm_port: 5985
ansible_shell_type: powershell
ansible_become: false
