# group_vars/windows_clients.yml
# WinRM connection settings for Windows targets

ansible_user: Administrator
ansible_password: "Admin@123"
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore
ansible_winrm_port: 5985
ansible_shell_type: powershell
ansible_become: false
addc_ip: "10.0.20.101"
domain_name: "cyberstrike.mil"
domain_password: "Admin@123"
ansible_become_method: runas
